<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="88143" started-at="2019-08-11T15:50:45Z" finished-at="2019-08-11T15:52:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="88143" started-at="2019-08-11T15:50:45Z" finished-at="2019-08-11T15:52:14Z">
      <class name="com.qa.TestLayer.TestLayer1">
        <test-method status="PASS" signature="initialization()[pri:0, instance:com.qa.TestLayer.TestLayer1@c81cdd1]" name="initialization" is-config="true" duration-ms="29099" started-at="2019-08-11T15:50:45Z" finished-at="2019-08-11T15:51:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="Logintest()[pri:0, instance:com.qa.TestLayer.TestLayer1@c81cdd1]" name="Logintest" duration-ms="6844" started-at="2019-08-11T15:51:15Z" finished-at="2019-08-11T15:51:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest -->
        <test-method status="PASS" signature="initialization()[pri:0, instance:com.qa.TestLayer.TestLayer1@c81cdd1]" name="initialization" is-config="true" duration-ms="14462" started-at="2019-08-11T15:51:21Z" finished-at="2019-08-11T15:51:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="FAIL" signature="Logintest2()[pri:0, instance:com.qa.TestLayer.TestLayer1@c81cdd1]" name="Logintest2" duration-ms="965" started-at="2019-08-11T15:51:36Z" finished-at="2019-08-11T15:51:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.Pagelayer.LoginPage.Login2(LoginPage.java:31)
at com.qa.TestLayer.TestLayer1.Logintest2(TestLayer1.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest2 -->
      </class> <!-- com.qa.TestLayer.TestLayer1 -->
      <class name="com.qa.TestLayer.TestLayer2">
        <test-method status="PASS" signature="initialization()[pri:0, instance:com.qa.TestLayer.TestLayer2@1fc2b765]" name="initialization" is-config="true" duration-ms="14629" started-at="2019-08-11T15:51:39Z" finished-at="2019-08-11T15:51:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="Logintest12()[pri:0, instance:com.qa.TestLayer.TestLayer2@1fc2b765]" name="Logintest12" duration-ms="1571" started-at="2019-08-11T15:51:54Z" finished-at="2019-08-11T15:51:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest12 -->
        <test-method status="PASS" signature="initialization()[pri:0, instance:com.qa.TestLayer.TestLayer2@1fc2b765]" name="initialization" is-config="true" duration-ms="17106" started-at="2019-08-11T15:51:55Z" finished-at="2019-08-11T15:52:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="FAIL" signature="Logintest22()[pri:0, instance:com.qa.TestLayer.TestLayer2@1fc2b765]" name="Logintest22" duration-ms="489" started-at="2019-08-11T15:52:12Z" finished-at="2019-08-11T15:52:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.Pagelayer.LoginPage.Login2(LoginPage.java:31)
at com.qa.TestLayer.TestLayer2.Logintest22(TestLayer2.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest22 -->
      </class> <!-- com.qa.TestLayer.TestLayer2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
